apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  user-db-password: {{ .Values.dbSecrets.userDbPassword | b64enc | quote }}
  room-db-password: {{ .Values.dbSecrets.roomDbPassword | b64enc | quote }}
  reservation-db-password: {{ .Values.dbSecrets.reservationDbPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.jwtSecret | b64enc | quote }}