version: '3.9'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/users_db
      - JWT_SECRET_KEY=super-secret-key
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-userdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
