# Global values
global:
  namespace: meeting-room
  environment: production

# Secrets for JWT and database passwords
jwtSecret: "ce8a7c37deef6ebf578e2971d9e06673214631baf629cc16e870b731bba4ff0c"
dbSecrets:
  userDbPassword: "postgres"
  roomDbPassword: "postgres"
  reservationDbPassword: "postgres"

# User Service configuration
userService:
  name: user-service
  image:
    repository: yasserzr/meeting-room-user-service
    tag: latest
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  port: 5000
  env:
    secretKey: "1d1a8ba2648f198a712c4996e5ee6207938ba0a0c83a5047"
    kafkaBootstrapServers: "kafka:9092"
    kafkaUsersTopic: "users-topic"

# Room Service configuration
roomService:
  name: room-service
  image:
    repository: yasserzr/meeting-room-room-service
    tag: latest
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  port: 5001
  env:
    secretKey: "1d1a8ba2648f198a712c4996e5ee6207938ba0a0c83a5047"
    kafkaBootstrapServers: "kafka:9092"
    kafkaRoomsTopic: "rooms-topic"

# Reservation Service configuration
reservationService:
  name: reservation-service
  image:
    repository: yasserzr/meeting-room-reservation-service
    tag: latest
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  port: 5002
  env:
    secretKey: "1d1a8ba2648f198a712c4996e5ee6207938ba0a0c83a5047"
    kafkaBootstrapServers: "kafka:9092"
    kafkaReservationsTopic: "reservations-topic"
    userServiceUrl: "http://user-service:5000"
    roomServiceUrl: "http://room-service:5001"

# Database configurations
databases:
  userDb:
    name: user-db
    image: postgres:15
    port: 5432
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    persistence:
      size: 1Gi
      storageClass: standard
  roomDb:
    name: room-db
    image: postgres:15
    port: 5432
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    persistence:
      size: 1Gi
      storageClass: standard
  reservationDb:
    name: reservation-db
    image: postgres:15
    port: 5432
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    persistence:
      size: 1Gi
      storageClass: standard

# Kafka configuration
kafka:
  name: kafka
  enabled: true
  replicas: 1
  image: confluentinc/cp-kafka:7.3.0
  port: 9092
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    size: 2Gi
    storageClass: standard
  zookeeper:
    name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.0
    port: 2181
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    persistence:
      size: 1Gi
      storageClass: standard

# Nginx Ingress configuration
nginx:
  name: nginx
  enabled: true
  replicas: 2
  image: nginx:latest
  port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  configMap:
    name: nginx-conf

# Monitoring configuration
monitoring:
  enabled: true
  aws:
    region: "us-east-1"
    accessKey: ""
    secretKey: ""
    cloudWatchLogGroup: "meeting-room-api-logs"
    cloudWatchAlarms:
      errorRateAlarm:
        name: "MeetingRoomAPIErrorRate"
        threshold: 5
        evaluationPeriods: 1
        period: 60
        comparisonOperator: "GreaterThanThreshold"
        namespace: "MeetingRoomAPI"
        metricName: "ErrorCount"
        statistic: "Sum"
  grafana:
    adminPassword: "admin123" # Should be changed in production
    dashboards:
      enabled: true
  loki:
    retention: 7d
    replicationFactor: 1
  fluentBit:
    buffer: 5MB