"""Update User model

Revision ID: 744795de42d4
Revises: 2ea5c7dd4bed
Create Date: 2025-04-20 17:38:44.297153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744795de42d4'
down_revision = '2ea5c7dd4bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Add the username column with a default value to avoid NOT NULL violations
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False, server_default='default_username'))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False, server_default='default_password'))
        batch_op.alter_column('username', server_default=None)  # Remove the default after adding the column
        batch_op.alter_column('password', server_default=None)  # Remove the default after adding the column
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
